version: "2"
services:
  ontario:
    image: kemele/ontario:0.3
    hostname: ontario
    container_name: ontario
    domainname: sdl
    volumes:
      - ./mappings:/mappings
      - ./configurations:/configurations
      - ./queries:/queries
      - ./results:/results
      - ./data/tsv:/data/tsv
      - ./data/json:/data/json
      - ./data/csv:/data/csv
    ports:
      - "5001:5000"
    environment:
      - CONFIG_FILE=/configurations/config.json
    networks:
      - osdl

  rdfstore1:
    image: kemele/virtuoso:7-stable
    hostname: gtfsrdf
    container_name: rdfstore
    domainname: sdl
    volumes:
      - ./data/rdf/gtfs-rdf:/data/toLoad
    ports:
      - "11385:8890"
      - "1116:1111"
    networks:
      - osdl

  rdfstore2:
    image: kemele/virtuoso:7-stable
    hostname: gtfsrdf5
    container_name: rdfstore5
    domainname: sdl
    volumes:
      - ./data/rdf/gtfs-rdf1:/data/toLoad
    ports:
      - "11386:8890"
      - "1117:1111"
    networks:
      - osdl

  rdbstore:
    image: mysql:5.7.16
    hostname: gtfsmysql
    container_name: rdbstore
    domainname: sdl
    volumes:
      - ./data/csv/gtfs-rdf:/data/csv/gtfs-rdf
      - ./data/tsv/drugbank:/data/tsv/drugbank
      - ./data/rdb/volumes/drugbank_mysql:/var/lib/mysql
      - ./data/rdb/drugbank:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: oeg
    ports:
      - "9000:3306"
    networks:
      - osdl


networks:
  osdl:
    external: false
