version: "2"
services:
  ontario:
    image: kemele/ontario:0.3
    hostname: ontario
    container_name: ontario
    domainname: sdl
    volumes:
      - ./mappings:/mappings
      - ./configurations:/configurations
      - ./queries:/queries
      - ./results:/results
      - ./data/csv:/data/csv
    ports:
      - "5001:5000"
    environment:
      - CONFIG_FILE=/configurations/config.json
    restart: always
    networks:
      - osdl

  spain:
    image: kemele/virtuoso:7-stable
    hostname: spainrdf
    container_name: spain
    domainname: sdl
    volumes:
#      - ./data/rdf/gtfs-rdf:/data/toLoad
      - ./data/rdf/spain:/data/toLoad
    ports:
      - "11385:8890"
      - "1116:1111"
    restart: always
    networks:
      - osdl

  belgium:
    image: kemele/virtuoso:7-stable
    hostname: belgiumrdf
    container_name: belgium
    domainname: sdl
    volumes:
#      - ./data/rdf/gtfs-rdf1:/data/toLoad
      - ./data/rdf/belgium:/data/toLoad
    ports:
      - "11386:8890"
      - "1117:1111"
    restart: always
    networks:
      - osdl

networks:
  osdl:
    external: false
